using System.Runtime.CompilerServices;

namespace COMP003A.Assignment1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Favorit,color blue!");
            Console.WriteLine("play sports!");
            Console.WriteLine("love to go camping!");
            Console.WriteLine("play video games!");
            Console.WriteLine("going to the beach with friends!");
            Console.WriteLine("My favorite baseball team is the giants!");
            Console.WriteLine("My favorite sport to play is basketball!");
            Console.WriteLine("Playing poker with my family!");
            Console.WriteLine("My favorite video game to play is madden that is football!");
            Console.WriteLine("My favorite tv show is supernatrual!");
            Console.WriteLine("My favorite movie to watch is Jaws!");
            Console.WriteLine("My Favorite foood is pizza!");
            Console.WriteLine("My favorite subject is math!");
            Console.WriteLine("My favorite animial is dogs!");
            Console.WriteLine("my favorite camp site is shaver lake!");
            Console.WriteLine("My favorite type of fish to eat is catfish!");
            Console.WriteLine("I have 3 pets!");
            Console.WriteLine("I have 3 younger siblings!");
            Console.WriteLine("The sport i played the best in is baseball!");
            Console.WriteLine("Im a quick learner!");
            Console.WriteLine("I have my driver license!");
            Console.WriteLine("I pay for my own car insurance!");
            Console.WriteLine("I enloy doing homework!");
            Console.WriteLine("I like going to the snow during winter!");
            Console.WriteLine("I've went to 2 other states in my lifetime!");
            Console.WriteLine("Im not a very quick at reading!");
            Console.WriteLine("I collect pokemon cards with my friends!");
            Console.WriteLine("I have a garden!");
            Console.WriteLine("I graduted high school in 2022!");
            Console.WriteLine("I enjoy working on cars during my free time!");
            Console.WriteLine("I been deep sea fishing 2 times!");
            Console.WriteLine("my least favorite sport is Boxing!");
            Console.WriteLine("The car that i drive is a Ford Edge!");
            Console.WriteLine("I play fantasy Football with my Family!");
            Console.WriteLine("Im very competitive when it comes to sports!");
            Console.WriteLine("I know how to weld!");
            Console.WriteLine("I play a lot of spades with my family!");
            Console.WriteLine("I am very easy to get along with!");
            Console.WriteLine("I Know how to build a fence!");
            Console.WriteLine("I know how to do concreat!");
            Console.WriteLine("I know how to do tile floring!");
            Console.WriteLine("I know how to do eletricale!");
            Console.WriteLine("I know how to drive a forklift!");
            Console.WriteLine("I know a little bit about construction!");
            Console.WriteLine("I been to one NFL game!");
            Console.WriteLine("I been to one profesinal baseball game!");
            Console.WriteLine("I enjoy going to the gym!");
            Console.WriteLine("the most i can benchpress is 200!");
            Console.WriteLine("the most i can squat is 450!");
            Console.WriteLine("The most i can deadlift is 500 without a belt!");
            Console.WriteLine("I Like to go hiking every now and then!");
            Console.WriteLine("I Like to go to the zoo with my family!");
            Console.WriteLine("My favorite holiday is Halloween!");
            Console.WriteLine("My favorite fishing spot is shaver lake!");
            Console.WriteLine("I been camping at the beach");
            Console.WriteLine("I like taking picture of Nature");
            Console.WriteLine("I like watching catch and coock youtube videos!");
            Console.WriteLine("I like working ahead on assinments if im able to");
            Console.WriteLine("Im trying to learn a diffrent language!");
            Console.WriteLine("This is my third year of college!");
            Console.WriteLine("I been trying to learn how to snowbored!");
            Console.WriteLine("I caught every fish there is in the vally!");
            Console.WriteLine("I was raised in lemoore my entire life!");
            Console.WriteLine("I been to the 5c summer camp that lemoore college has for kids!");
            Console.WriteLine("I was never good in school until i got glasses!");
            Console.WriteLine("I like to play chess againts my friend!");
            Console.WriteLine("I know how to drive a truck with a trailer1");
            Console.WriteLine("I like to Lisren to every type of music!");
            Console.WriteLine("My favorite artist to listen to is Melly!");
            Console.WriteLine("The song i Listen to the Most is Mocking bird!");
            Console.WriteLine("I like to grill tritip for family events!");
            Console.WriteLine("I been saving up to buy another car!");
            Console.WriteLine("I coach my siblings in sports so they can be prepaired!");
            Console.WriteLine("I enjoy playing vollyball with my family when we go to the park!");
            Console.WriteLine("I dont know a lot about computers!");
            Console.WriteLine("My birth month is september so my zodiac sign is a virgo!");
            Console.WriteLine("my favorit energy drink are Monsters!");
            Console.WriteLine("my favorit resturant to eat at is applebees!");
            Console.WriteLine("my least favorite animal is a jelly fish!");
            Console.WriteLine("My most favorite animal in the wild is a tiger!");
            Console.WriteLine("I trie collecting rare coins!");
            Console.WriteLine("My favorite coffe shop is starbucks1");
            Console.WriteLine("The longest i been camping is a week!");
            Console.WriteLine("I cant name all 50 states!");
            Console.WriteLine("My least favorite game to play is Minecraft!");
            Console.WriteLine("Im trying to build a pc tower from scratch!");
            Console.WriteLine("I dont know how to drive stick shift!");
            Console.WriteLine("My dream car is a mustange but i want to build it from scratch!");
            Console.WriteLine("I enjoy learning diffrent culture!");
            Console.WriteLine("My favorite chips are pringles BBQ!");
            Console.WriteLine("my favorite soda is dr pepper!");
            Console.WriteLine("the shoe brand that i like is Nike!");
            Console.WriteLine("My favorit NBA player is Kobe!");
            Console.WriteLine("I played sports my entire life!");
            Console.WriteLine("I can do the alphabet back words!");
            Console.WriteLine("I enjoy star gazing when i go camping!");
            Console.WriteLine("my least favorit movie is star wars!");
            Console.WriteLine("I enjoy spending as much time with my friends and family!");
            Console.WriteLine("I built a trailer in my agriculture class in high school!");
            Console.WriteLine("I help people who need it if im able to understand what they need done");
            Console.WriteLine("I know how to repair video game consoles!");
        }
    }
}
